# behaviors:
#   EvaderAgent:
#     trainer_type: ppo
#     max_steps: 1e6
#     time_horizon: 64
#     summary_freq: 10000
#     hyperparameters:
#       batch_size: 64
#       buffer_size: 12000
#       learning_rate: 3.0e-4
#       beta: 5.0e-3
#       epsilon: 0.2
#       lambd: 0.95
#       num_epoch: 3
#     network_settings:
#       normalize: false
#       hidden_units: 128
#       num_layers: 2
#     reward_signals:
#       extrinsic:
#         gamma: 0.99
#         strength: 1.0
#   ChaserAgent:
#     trainer_type: ppo
#     max_steps: 1e6
#     time_horizon: 64
#     summary_freq: 10000
#     hyperparameters:
#       batch_size: 64
#       buffer_size: 12000
#       learning_rate: 3.0e-4
#       beta: 5.0e-3
#       epsilon: 0.2
#       lambd: 0.95
#       num_epoch: 3
#     network_settings:
#       normalize: false
#       hidden_units: 128
#       num_layers: 2
#     reward_signals:
#       extrinsic:
#         gamma: 0.99
#         strength: 1.0



behaviors:
  EvaderAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2.5e6
    time_horizon: 128
    summary_freq: 100000

  ChaserAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2.5e6
    time_horizon: 128
    summary_freq: 100000
